vich_uploader:
    db_driver: orm

    mappings:
        house_images:
            uri_prefix: /images/house
            upload_destination: '%kernel.project_dir%/public/images/house'
            namer: Vich\UploaderBundle\Naming\SmartUniqueNamer
           
    metadata:
        type: attribute